## Basic operations

In [1]:
import numpy as np

In [6]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [22]:
python_list=list(range(100))
python_list[0:5]

[0, 1, 2, 3, 4]

In [23]:
import sys

sys.getsizeof(python_list[0])*len(python_list)

2800

In [25]:
numpy_array=np.arange(100)
numpy_array[0:5]

array([0, 1, 2, 3, 4])

In [26]:
numpy_array.nbytes

800

In [28]:
# numpy 2numpy_list addition 
n1=np.array([1,2,3])
n2=np.array([4,5,6])

n1+n2

array([5, 7, 9])

In [34]:
# python 2list_addition
l1=[1,2,3] 
l2=[4,5,6] 
print(l1+l2) # it combining 2 list so use loops

print()

for x,y in zip(l1,l2):
    print(x+y,end=" ")

[1, 2, 3, 4, 5, 6]

5 7 9 

In [3]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a1+a2

array([5, 7, 9])

In [4]:
a2-a1

array([3, 3, 3])

In [5]:
a1*a2

array([ 4, 10, 18])

In [6]:
a1/a2

array([0.25, 0.4 , 0.5 ])

In [1]:
import numpy as np

In [2]:
rev_q=np.array([1,2,3])
rev_q.ndim

1

In [4]:
rev_q=np.array([[1,2,3],[4,5,6]])
rev_q.ndim

2

In [5]:
rev_q

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
rev_q[:,2]=-2

In [10]:
rev_q

array([[ 1,  2, -2],
       [ 4,  5, -2]])

In [ ]:
rev_q=np.array([[1,2,3],[4,5,6]],dtype=np.float64)
rev_q.itemsize #each num size occuping or byte size

8

In [14]:
rev_q.size

6

In [15]:
rev_q.shape

(2, 3)

In [16]:
np.sort(rev_q)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
np.sort(rev_q,axis=None)

array([1., 2., 3., 4., 5., 6.])

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.arange(20,30)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [33]:
n=np.array([[1,2,3],[4,5,6]])
n

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
n.ravel()

array([1, 2, 3, 4, 5, 6])

In [37]:
n.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
n.max()

np.int64(6)

In [39]:
n.min()

np.int64(1)

In [40]:
n.sum(axis=1)

array([ 6, 15])

In [41]:
n.sum(axis=0)

array([5, 7, 9])

In [43]:
n1=np.array([1,4,16])
np.sqrt(n1)

array([1., 2., 4.])

In [44]:
np.square(n1)

array([  1,  16, 256])

In [45]:
np.std(n1)

np.float64(6.48074069840786)

## matrix operations

In [ ]:
import numpy as np

In [ ]:
#  usa india china
q1=np.array([
    [200,220,250],  # Product A
    [150,180,210],  # Product B
    [300,330,360]   # Product C
])

q2=np.array([
    [209,231,259],   # Product A
    [155,192,222],   # Product B
    [310,340,375]    # Product C
])

In [7]:
q1 + q2

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [8]:
q2 - q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [ ]:
(q2 - q1)*100/q1  # percentage increased

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [10]:
prices = np.array([
    [10, 12, 11],  # Prices for Product A in different regions
    [8,  9,  10],  # Prices for Product B
    [15, 16, 17]   # Prices for Product C
])

q1_revenue=q1 * prices
q1_revenue

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

In [12]:
q1_discount=q1_revenue *0.2
q1_discount

array([[ 400.,  528.,  550.],
       [ 240.,  324.,  420.],
       [ 900., 1056., 1224.]])

In [14]:
net_revenue = q1_revenue - q1_discount
net_revenue

array([[1600., 2112., 2200.],
       [ 960., 1296., 1680.],
       [3600., 4224., 4896.]])

In [15]:
np.sum(q1_discount)

np.float64(5642.0)

In [18]:
features = np.array([
    [2000,3], # house 1
    [1800,2]  # house 2
])
weight = np.array([150,50000])
2000*150 + 3*50000

450000

In [19]:
np.dot(features , weight)

array([450000, 370000])

In [20]:
c = np.array([1,2,3])
d = np.array([4,5,6])
np.cross(c,d)

array([-3,  6, -3])

## slicing stacking

In [23]:
import numpy as np

In [24]:
a = np.array([1,2,3,4])

In [26]:
a[0:2]

array([1, 2])

In [27]:
a[2:]

array([3, 4])

In [28]:
a[-1]

np.int64(4)

In [29]:
a[-2]

np.int64(3)

In [30]:
a[-2:]

array([3, 4])

In [31]:
b = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

In [32]:
b[1,2]

np.int64(6)

In [35]:
b[2,0]

np.int64(7)

In [36]:
b[-1]

array([7, 8, 9])

In [37]:
b[-1,0:2]

array([7, 8])

In [38]:
b[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [40]:
### vstack, hstack
# Customer ID, Name
c = np.array([
    [101, 'Mira'],
    [102, 'Abdul'],
    [103, 'Andrea']
])
# Customer Id, Purchase Amount, Purchase Date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01']
])

In [49]:
np.hstack((c,d))

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Abdul', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08-01']], dtype='<U32')

In [50]:
c

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea']], dtype='<U21')

In [52]:
e = np.array([
    [104, 'Venkat'],
    [105, 'John'],
    [106, 'Kathy'],
])
e

array([['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

In [54]:
np.vstack((c,e))

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

In [60]:
# vsplit, hsplit
transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
    [103, 'Fatima', 300.75, '2023-08-01'],
    [104, 'David', 400.20, '2023-08-03'],
    [105, 'Aryan', 330.1, '2023-08-04'],
])

a , b = np.hsplit(transactions, [3])

In [61]:
a

array([['101', 'Mohan', '250.5'],
       ['102', 'Bob', '150.0'],
       ['103', 'Fatima', '300.75'],
       ['104', 'David', '400.2'],
       ['105', 'Aryan', '330.1']], dtype='<U32')

In [62]:
b

array([['2023-08-01'],
       ['2023-08-02'],
       ['2023-08-01'],
       ['2023-08-03'],
       ['2023-08-04']], dtype='<U32')

In [66]:
x,y=np.vsplit(transactions, [2])

In [67]:
x

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02']], dtype='<U32')

In [68]:
y

array([['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [70]:
monthly_sales=np.array([30,33,35,28,42])

In [71]:
result = monthly_sales < 32
result

array([ True, False, False,  True, False])

In [72]:
monthly_sales[result]

array([30, 28])

In [73]:
monthly_sales.max()

np.int64(42)

In [78]:
index=np.argmax(monthly_sales) #index pf 42
index

np.int64(4)

In [79]:
# Now print a transaction with a maximum amount
transactions

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [85]:
t_index=np.argmax(transactions[:,2].astype(float))
t_index

np.int64(3)

In [87]:
transactions[t_index]

array(['104', 'David', '400.2', '2023-08-03'], dtype='<U32')

In [88]:
transactions[transactions[:,0]=="102"]

array([['102', 'Bob', '150.0', '2023-08-02']], dtype='<U32')

In [90]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])