In [1]:
import numpy as np

In [6]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [22]:
python_list=list(range(100))
python_list[0:5]

[0, 1, 2, 3, 4]

In [23]:
import sys

sys.getsizeof(python_list[0])*len(python_list)

2800

In [25]:
numpy_array=np.arange(100)
numpy_array[0:5]

array([0, 1, 2, 3, 4])

In [26]:
numpy_array.nbytes

800

In [28]:
# numpy 2numpy_list addition 
n1=np.array([1,2,3])
n2=np.array([4,5,6])

n1+n2

array([5, 7, 9])

In [34]:
# python 2list_addition
l1=[1,2,3] 
l2=[4,5,6] 
print(l1+l2) # it combining 2 list so use loops

print()

for x,y in zip(l1,l2):
    print(x+y,end=" ")

[1, 2, 3, 4, 5, 6]

5 7 9 

In [3]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a1+a2

array([5, 7, 9])

In [4]:
a2-a1

array([3, 3, 3])

In [5]:
a1*a2

array([ 4, 10, 18])

In [6]:
a1/a2

array([0.25, 0.4 , 0.5 ])