In [1]:
import numpy as np

In [6]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [22]:
python_list=list(range(100))
python_list[0:5]

[0, 1, 2, 3, 4]

In [23]:
import sys

sys.getsizeof(python_list[0])*len(python_list)

2800

In [25]:
numpy_array=np.arange(100)
numpy_array[0:5]

array([0, 1, 2, 3, 4])

In [26]:
numpy_array.nbytes

800

In [28]:
# numpy 2numpy_list addition 
n1=np.array([1,2,3])
n2=np.array([4,5,6])

n1+n2

array([5, 7, 9])

In [34]:
# python 2list_addition
l1=[1,2,3] 
l2=[4,5,6] 
print(l1+l2) # it combining 2 list so use loops

print()

for x,y in zip(l1,l2):
    print(x+y,end=" ")

[1, 2, 3, 4, 5, 6]

5 7 9 

In [3]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a1+a2

array([5, 7, 9])

In [4]:
a2-a1

array([3, 3, 3])

In [5]:
a1*a2

array([ 4, 10, 18])

In [6]:
a1/a2

array([0.25, 0.4 , 0.5 ])

In [1]:
import numpy as np

In [2]:
rev_q=np.array([1,2,3])
rev_q.ndim

1

In [4]:
rev_q=np.array([[1,2,3],[4,5,6]])
rev_q.ndim

2

In [5]:
rev_q

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
rev_q[:,2]=-2

In [10]:
rev_q

array([[ 1,  2, -2],
       [ 4,  5, -2]])

In [ ]:
rev_q=np.array([[1,2,3],[4,5,6]],dtype=np.float64)
rev_q.itemsize #each num size occuping or byte size

8

In [14]:
rev_q.size

6

In [15]:
rev_q.shape

(2, 3)

In [16]:
np.sort(rev_q)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
np.sort(rev_q,axis=None)

array([1., 2., 3., 4., 5., 6.])

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.arange(20,30)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [33]:
n=np.array([[1,2,3],[4,5,6]])
n

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
n.ravel()

array([1, 2, 3, 4, 5, 6])

In [37]:
n.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
n.max()

np.int64(6)

In [39]:
n.min()

np.int64(1)

In [40]:
n.sum(axis=1)

array([ 6, 15])

In [41]:
n.sum(axis=0)

array([5, 7, 9])

In [43]:
n1=np.array([1,4,16])
np.sqrt(n1)

array([1., 2., 4.])

In [44]:
np.square(n1)

array([  1,  16, 256])

In [45]:
np.std(n1)

np.float64(6.48074069840786)