### Corizo

In [2]:
def print_lyrics():
    print("hello")
    print("fine")

def repeat_lyrics():
    print_lyrics()
    print_lyrics()

repeat_lyrics()   


hello
fine
hello
fine


In [2]:
def add(a, b):
    print(a + b)

add(2, 7)
print("hi")

9
hi


In [ ]:
def fact(x):
    if x==0 or x==1:
        return 1
    else:
        return x * fact(x-1)
    
en=int(input("Enter the number:"))
if en <= 0:
    print(f"{en}: this number is not allowed,typer some other number")
else:
    print(f"The factorial of {en} is:{fact(en)}")    
    
# print(fact(4))

In [20]:
def f(n):
    result=1
    for i in range(1,n+1):
        result*=i
        print(result)
    return result

f(4)

1
2
6
24


24

In [21]:
a=2
b=1
a=b
a

1

In [22]:
def recurse(n,s):
    if n==0:
        print(s)
    else:
        recurse((n-1),n+s)
recurse(3,0)        

6


In [23]:
for i in range(1,20,2):
    print(i)

1
3
5
7
9
11
13
15
17
19


In [25]:
for i in range(1,10):
    print(i,end="-")

1-2-3-4-5-6-7-8-9-

In [2]:
for i in range(-1,-10-1,-1):
    print(i)

-1
-2
-3
-4
-5
-6
-7
-8
-9
-10


In [34]:
def count(n):
    while n>0:
        print(n)
        n-=1
    print("blast off")    
count(5)   

5
4
3
2
1
blast off


In [36]:
while True:
    line=input(">")
    if line=="Done":
        break
    print(line)

g
f
d
gg


In [38]:
n=1
while True:
    if n>=11:
        break
    print(n)
    n+=1


1
2
3
4
5
6
7
8
9
10


In [47]:
# Strings

fruit="Banana"
print(fruit)

print(fruit[2])

print(fruit[-3])

print(fruit[::-1])

Banana
n
a
ananaB


In [4]:
fruits="Pineapple"
for i in fruits:
    print(i,end="")
len(fruits)

Pineapple

9

In [52]:
fruits="Pineapple"
n=0
while n<len(fruits):
    print(fruits[n])
    n+=1
 
    

P
i
n
e
a
p
p
l
e


In [59]:
#Concat
first_name="Thirumalesh"
last_name="V"
full_name=first_name+last_name
print(full_name)

len(last_name*4)

ThirumaleshV


4

In [62]:
prefix="JSPD"
suffix="ack"
suffix2="aok"

for letters in prefix:
    if letters=="J" or letters=="P":
        print(letters+suffix)
    else:
        print(letters+suffix2)        

Jack
Saok
Pack
Daok


In [64]:
s="Monty Python"
print(s[2:8])
print(s[-1:-5:-1])

nty Py
noht


In [65]:
h="Hello"
print("T"+h[1:])

Tello


In [ ]:
name="Thirumaleh"
if "h" in name:
    print("yes")
else:
    print("No")        

yes


In [6]:
W="THIRUMALESH"
print(W.find('H',2))
print(W.find('o'))
print(W.find('RU'))


10
-1
3


In [77]:
name="Thiru"
new=name.upper()
print(new)


THIRU


In [78]:
#lists
cheese=["chader","milk"]
print(cheese)

['chader', 'milk']


In [81]:
num=[5,10]
for i in range(len(num)):
    num[i]*=2
print(num)

[10, 20]


In [18]:
num=[5,10]
for i in num:
    print(type(i))

<class 'int'>
<class 'int'>


In [85]:
t=[True,"Hello",3,["fruit","vegi"]]
t[3][1]

'vegi'

In [88]:
def palindrome(n):
    if n==n[::-1]:
        print(n,"is a 'palindrome'")
    else:
        print(f"{n}is not a palindrome")
take=input("Enter name to check:")
palindrome(take)            

HelleH is a 'palindrome'


In [6]:
che=[1,2,3,4,5,6,7,8,9,10]
che[-2:-5:-1]

[9, 8, 7]

In [15]:
t=["a","b","c","d","e","f","A"]
t[1:3]=["x","y"]
t.extend(["t","r"])
t.sort()
t

['A', 'a', 'd', 'e', 'f', 'r', 't', 'x', 'y']

In [23]:
def tot(n):
    total=0
    for i in n:
        total+=i
    print(type(total))    
    return total    

tot([1,2,3,4])    

<class 'int'>


10

In [25]:
def upper(s):
    lis=[]
    for i in s:
        if i.isupper():
            lis.append(i)
    return lis
upper(["e","A","q","B"])        


['A', 'B']

In [28]:
h1="Tanvi"
h2="tanvi"
print(id(h1))
print(id(h2))

2210660856288
2210660988752


In [32]:
t1=[1,2,3,]
t2=t1+[4]
t2

[1, 2, 3, 4]

In [ ]:
# string to list
s="spam"
t=list(s)
t

['s', 'p', 'a', 'm']

In [51]:
s="i like to, play"
t=s.split()
type(t)
len(t)
t


['i', 'like', 'to,', 'play']

In [11]:
# list to string 
t=["a","b"]
s=" ".join(t)
type(s)
print(s)

a b


In [13]:
# Dictionaries
di={"one":1,"two":2,"three":3}
v=di.values()
v
di["one"]=11
di


{'one': 11, 'two': 2, 'three': 3}

In [76]:
def rep(n):
    d={}
    for i in n:
        if i not in d:
            d[i]=1
        else:
            d[i]+=1
    return d

rep("thirumalesh")           
rep("AABCCCC")           

{'A': 2, 'B': 1, 'C': 4}

In [ ]:
t=123
h=str(t)

str

In [ ]:
# tuples
t=(1,2,3)
t[1]
new_t=(4,5)+t[:]
new_t

(4, 5, 1, 2, 3)

In [95]:
a=1
b=2
def switch(a,b):
    x=a
    a=b
    b=x
    print("a is:",a,"B is :",b)

switch(a,b)

t=1
v=2
t,v=v,t
print(v)

a is: 2 B is : 1
1


In [99]:
email="thiurmalesh4323@gmail.com"
username,domain=email.split("@")
print(username)
print(domain)

thiurmalesh4323
gmail.com


In [105]:
t=(1,2,3)
type(t)
max(t)
sum([1,2,3])

6

In [111]:
t=[("a",0),("b",1)]
for letter,number in t:
    p=letter,number
    print(p)
print(type(p))

('a', 0)
('b', 1)
<class 'tuple'>


In [19]:
# dict to tuples
dict={"a":1,"b":2,"c":3}
t=dict.items()
print(type(t))
ch1=list(dict.items())
ch2=tuple(dict.items())
print(type(ch1))
print(type(ch2))

for key ,value in t:
    print(key,value)

ch1[0]


<class 'dict_items'>
<class 'list'>
<class 'tuple'>
a 1
b 2
c 3


('a', 1)

In [20]:
del dict

In [21]:
# tuples to dict 
t=(("a",0),("b",2))
d=dict(t)
d
type(t)
d

{'a': 0, 'b': 2}

In [22]:
emp_id=[1,2,3,4,5]
emp_name=["A","B","C","D"]
emp_info=dict(zip(emp_id,emp_name))
print(emp_info)

{1: 'A', 2: 'B', 3: 'C', 4: 'D'}


In [ ]:
s="abc"
t=[0,1,2]
for pair in zip(s,t):
    print(pair)
print(type(pair))    
print()

p=zip(s,t)
for i in p:
    print(i)


list(zip(s,t))

q=tuple(zip("hello","python"))
p=list(zip("hello","python"))

d = dict(zip("abc", range(3)))


('a', 0)
('b', 1)
('c', 2)
<class 'tuple'>

('a', 0)
('b', 1)
('c', 2)


(('h', 'p'), ('e', 'y'), ('l', 't'), ('l', 'h'), ('o', 'o'))

In [156]:
ord("H")

72

In [5]:
l=[1,2,3,4,5]
for i in range(len(l)):
    l[i] += 1
print(l)

[2, 3, 4, 5, 6]


### Numpy

In [9]:
import numpy as np

data=np.random.randn(2,3)
print(data)

[[ 1.93403013 -0.64699528  0.85985235]
 [ 0.11830092  1.3759666  -0.92619609]]


In [3]:
data*10

array([[  1.91489695,   9.7543656 ,  14.77170059],
       [-19.01038688,  -3.73733015, -10.89709831]])

In [4]:
data.shape

(2, 3)

In [14]:
#list to numpy
data=[3,2,4,5,1]
arr1=np.array(data)
print(type(arr1))

<class 'numpy.ndarray'>


In [15]:
data=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.shape

(2, 4)

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])