#### is and isnot

In [1]:
a=[1,2,3]
b=a
c=[1,2,3]
print(a is b)
print(a is c)
print(a == c)

print(a is not c)

True
False
True
True


##### Smaller integers between -5 to 256 is true,
##### Larger integers than -5 to 256 is false 

In [2]:
x=10
y=10  
print(x is y)

True


In [3]:
a=300
b=300
print(a is b)

False


In [3]:
#Membership operator in , not in
h=["A","B"]
print("B" in h)
print("B" not in h)


True
False


In [4]:
#isinstance
y=isinstance(6,int)
y

True

In [8]:
print(int(eval(input("Enter the numbers to calculate:"))))

11


#### Strings

In [9]:
text="Hello world"
print(text.find("world"))

6


In [10]:
s="hello world"
print(s.split("o",1))

['hell', ' world']


In [12]:
a="ABCD"
print(a[-1:-5:-1])
print(len(a))

DCBA
4


In [16]:
address='''bengaluru,
Karnataka'''
print(address)

bengaluru,
Karnataka


In [21]:
s1="hello"
s2="world"
print(s1,"",s2)

hello  world


In [29]:
s="total states"
n=20
print(s+str(n))

total states20


In [32]:
text="Hello how are you"
t=text.split()[1]
t

'how'

#### lists

In [34]:
items=["Pasta","Bread","fruits"]
items[1]

'Bread'

In [36]:
items[1]="chips"
items

['Pasta', 'chips', 'fruits']

In [37]:
items[-1]

'fruits'

In [38]:
#append
items=["Pasta","Bread","fruits"]
items.append("Butter")
items

['Pasta', 'Bread', 'fruits', 'Butter']

In [60]:
#Extend
items=["Pasta","Bread","fruits"]
items.extend(["Mange","choco"])
items

['Pasta', 'Bread', 'fruits', 'Mange', 'choco']

In [61]:
p=items.reverse() #modifys original list
print(items)

['choco', 'Mange', 'fruits', 'Bread', 'Pasta']


In [62]:
items.remove("choco")
print(items)

['Mange', 'fruits', 'Bread', 'Pasta']


In [65]:
#insert at any index
items=["bread","pasta","fruits"]
items.insert(1,"butter")
print(items)
len(items)

['bread', 'butter', 'pasta', 'fruits']


4

In [66]:
#pop
items=["bread","pasta","fruits"]
items.pop(2)
items

['bread', 'pasta']

In [67]:
#clear
items=["bread","pasta","fruits"]
items.clear()
print(items)

[]


In [77]:
#del
items=["bread","pasta","fruits"]
del items
# print(items)

In [ ]:
#functions
print(min([3,1,2]))
print(max([3,1,2]))
print(sum([3,1,2]))
print(all([True,1]))  #empty list is true
print(any([False,1])) #empty list is false

1
3
6
True
True


In [ ]:
#if
num=int(input("Enter the number:"))
if num%2==0:
    print("the number is even")
else:
    print("the number is odd")    

the number is even


In [1]:
x=10
if not(x>0):
    print("x is not greater")
else:
    print("x is greater")    

x is greater


In [2]:
p="hello"
print(p.isupper())

False


In [5]:
5//2

2

In [8]:
indian=["somosa","dosa"]
chinese=["eggroll","friedrice"]
italian=["pizza","pasta"]

dish1=input("Enter the dish name:")
dish=dish1.lower()

if dish in indian:
    print("the dish is indian")
elif  dish in chinese:
    print("the dish is chinese")
elif  dish in italian:
    print("the dish is italian")
else:
    print("i don't know")        


the dish is italian


In [16]:
word="python"

x=""
for i in word:
    x=x+i
    print(x)

p
py
pyt
pyth
pytho
python


In [17]:
#for

exp=[1,2,3,4]
total=0
for i in exp:
    total+=i
print(total)     

10


In [20]:
for i in range(1,11):
    if i == 5:
        continue
    else:
        print(i)

1
2
3
4
6
7
8
9
10


In [24]:
for i in range(1,11):
    if i == 7:
      pass
      print(i)

7


In [25]:
for i in range(1,5):
    if i==2:
        pass
    print(i)

1
2
3
4


In [26]:
exp=[10,20,30,40,50]
total=0
for i in range(len(exp)):
    print(f"month:{i+1},expenses:{exp[i]}")
    total+=exp[i]

print("total expenses is",total)    



month:1,expenses:10
month:2,expenses:20
month:3,expenses:30
month:4,expenses:40
month:5,expenses:50
total expenses is 150


In [27]:
bus_location="dommasandra"
locations=["sopura","yamara","T.C halli","dommasandra","dommasandra circle"]

for i in locations:
    if i == bus_location:
        print("bus has stopped at dommasandra")
    else:
        print("bus didn't stopped at",i)    

bus didn't stopped at sopura
bus didn't stopped at yamara
bus didn't stopped at T.C halli
bus has stopped at dommasandra
bus didn't stopped at dommasandra circle


In [28]:
#while

i=0
while i<=10:
    print(i)
    i+=1

0
1
2
3
4
5
6
7
8
9
10


In [30]:
while True:
    num=int(input("enter any number:"))
    if num == 0:
        break

In [ ]:
for i in range(1,5):
    pass
    print(i)

1
2
3
4


In [33]:
x=10
if x>5:
    pass

In [44]:
#functions
def cal(e):
    total=0
    for i in range(len(e)):
        total+=e[i]
    return total    

print(cal([1,2,3,4]))   
h1=[1,2,3,5]
print(cal(h1))

10
11


In [48]:
#gobal var
x=10

def fu():
    global x
    x=1
    print(x)

fu()    
print(x)

1
1


In [7]:
def sum(a=5,b=6):
    total=a+b
    return total

n=sum(a=3,b=1)
n

4

In [ ]:
#list to dictionary

emp_id=[1,2,3]
emp_name=["A","B","C"]
emp_info={}
for i in range(len(emp_id)):
    emp_info[emp_id[i]]=emp_name[i]
emp_info    

{1: 'A', 2: 'B', 3: 'C'}

In [10]:
list_tuple=[("x",1),("y",2)]
my={}
for key,value in list_tuple:
    my[key]=value

my    

{'x': 1, 'y': 2}

In [34]:
#Dictionary
d={"tom":1,"rob":2,"joe":3}
d["tom"]
d["sam"]=4
print(d)

{'tom': 1, 'rob': 2, 'joe': 3, 'sam': 4}


In [35]:
del d["sam"]
print(d)

{'tom': 1, 'rob': 2, 'joe': 3}


In [36]:
print(d.keys())
print(d.values())

dict_keys(['tom', 'rob', 'joe'])
dict_values([1, 2, 3])


In [37]:
for i in d:
    print("key:",i,"value:",d[i])

key: tom value: 1
key: rob value: 2
key: joe value: 3


In [38]:
print("tom" in d)

True


In [44]:
t=d.items()
print(type(t))
print(t)

<class 'dict_items'>
dict_items([('tom', 1), ('rob', 2), ('joe', 3)])


In [2]:
d={"a":1,"b":2}
print(d.get("a"))
print(d.get("c","Not there"))
print(d.get("c"))

1
Not there
None


In [32]:
d.clear()

In [5]:
d={"a":1,"b":2}
v=d.pop("a")
print(v)
print(d)


1
{'b': 2}


In [6]:
#Tuple
point=(5,9)
point

(5, 9)

In [9]:
tuple=(1,2,3,4,5,2,2)
print(tuple.count(2))
print(tuple.index(3))

3
2


In [10]:
t1=(1,2,3)
t2=(1,2,4)
print(t1<t2)

True


In [11]:
t1=(1,2)
print(t1*2)

(1, 2, 1, 2)


In [3]:
import calendar
cal=calendar.month(2004,2)
print(cal)

   February 2004
Mo Tu We Th Fr Sa Su
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28 29



In [4]:
print(calendar.isleap(2016))

True


In [2]:
#modules
import math
print(math.sqrt(16))
print(math.pow(2,5))
print(math.floor(2.5))
print(math.pi)
print(math.ceil(2.2))
dir(math)

4.0
32.0
2
3.141592653589793
3


['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'cbrt',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'exp2',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fma',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'sumprod',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [3]:
for i in dir(math):
    print(i)

__doc__
__loader__
__name__
__package__
__spec__
acos
acosh
asin
asinh
atan
atan2
atanh
cbrt
ceil
comb
copysign
cos
cosh
degrees
dist
e
erf
erfc
exp
exp2
expm1
fabs
factorial
floor
fma
fmod
frexp
fsum
gamma
gcd
hypot
inf
isclose
isfinite
isinf
isnan
isqrt
lcm
ldexp
lgamma
log
log10
log1p
log2
modf
nan
nextafter
perm
pi
pow
prod
radians
remainder
sin
sinh
sqrt
sumprod
tan
tanh
tau
trunc
ulp


In [ ]:
#exception handling
print(1/0)

ZeroDivisionError: division by zero

In [3]:
print("a"+2)

TypeError: can only concatenate str (not "int") to str

In [6]:
x=int(input("enter the number"))
y=int(input("enter the number"))
z=x/y
print("div by:",z)

ZeroDivisionError: division by zero

In [6]:
x=int(input("enter the number"))
y=int(input("enter the number"))
try:
    z=x/y
except Exception as e:
    print("exception occured:",type(e).__name__)
    z=None
finally:
    print("finished")    
print("Division is:",z)       

exception occured: ZeroDivisionError
finished
Division is: None


In [10]:
#binary number
n=7
format(n,"b")

'111'

In [12]:
s="i eat 10 apples"
s=s.replace("apples","mangoes")
s=s.replace("10","5")
s

'i eat 5 mangoes'

In [15]:
s="i eat 10 apples"
s=s.replace("apples","mangoes").replace("10","5")
s

'i eat 5 mangoes'

In [16]:
A=["A","C","B","E","D","F"]
A.sort()
A

['A', 'B', 'C', 'D', 'E', 'F']

In [18]:
for i in range(1,5):
    s=""
    for j in range(i):
        s+="* "
    print(s)

* 
* * 
* * * 
* * * * 


In [22]:
l1=[1,2,3]
l2=[4,5,6]
for i in l1:
    for j in l2:
        print(i,j)
    print()    

1 4
1 5
1 6

2 4
2 5
2 6

3 4
3 5
3 6



In [30]:
#patterns
n=5
for i in range(n):
    for j in range(n):
        if i==0 or j==0 or j==n-1 or i==n-1:
            print("*",end=" ")
        else:
            print(" ",end=" ")
    print()                     

* * * * * 
*       * 
*       * 
*       * 
* * * * * 


In [31]:
#pattern
for i in range(5):
    for j in range(5):
        print("*",end=" ")
    print()    

* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


In [4]:
for i in range(5):
    for j in range(i+1):
        print("*",end=" ")
    print()    

* 
* * 
* * * 
* * * * 
* * * * * 


In [9]:
n=5
for i in range(n):
    for j in range(n-i):
        print(" ",end=" ")
    for  j in range(i+1):
        print("*",end=" ")
    print()    

          * 
        * * 
      * * * 
    * * * * 
  * * * * * 


In [16]:
n=5
for i in range(n):
    for j in range(n-i):
        print(" ",end=" ")
    for j in range(i+1):
        print("*",end=" ")
    for j in range(i):
        print("*",end=" ")    
    print()    

          * 
        * * * 
      * * * * * 
    * * * * * * * 
  * * * * * * * * * 


In [14]:
n=5
for i in range(n):
    for j in range(i+1):
        print(" ",end=" ")
    for j in range(n-i):
        print("*",end=" ") 
    for j in range(n-i-1):
        print("*",end=" ")        
    print()    

  * * * * * * * * * 
    * * * * * * * 
      * * * * * 
        * * * 
          * 


In [22]:
n=5
for i in range(n-1):
    for j in range(n-i):
        print(" ",end=" ")
    for j in range(i+1):
        print("*",end=" ")
    for j in range(i):
        print("*",end=" ")
    print()    
for i in range(n):
    for j in range(i+1):
        print(" ",end=" ")
    for j in range(n-i):
        print("*",end=" ") 
    for j in range(n-i-1):
        print("*",end=" ")         
    print()    

          * 
        * * * 
      * * * * * 
    * * * * * * * 
  * * * * * * * * * 
    * * * * * * * 
      * * * * * 
        * * * 
          * 


In [10]:
#sets
s={2,1,4,2}
s

{1, 2, 4}

In [11]:
s.add(5)
s

{1, 2, 4, 5}

In [ ]:
s.remove(4) #rises error if not found
s

{1, 2, 5}

In [14]:
s.discard(4)# no errors if not found
s

{1, 2, 5}

In [15]:
s.pop()
s

{2, 5}

In [16]:
s.clear()

In [ ]:
#union()
#intersection()
#difference()

In [18]:
x=len(set("banana"))
x

3

In [26]:
import random
num=random.randint(1,100) #random number between 1 to 100
print(num)

7


In [27]:
num=random.uniform(1,100)# random flot number between 1 to 100
num

43.057435982955894

In [ ]:
i=random.randrange(10,20,2) #random value 10,12,14,16,18
i

12

In [29]:
fruits=["apple","grapes","orange","banana"]
print(random.choice(fruits))

banana


In [31]:
#printing ascii 
ascii_number=65
row=7
for i in range(row):
    for j in range(0,i+1):
        chra=chr(ascii_number)
        print(chra,end=" ")
        ascii_number+=1
    print()    


A 
B C 
D E F 
G H I J 
K L M N O 
P Q R S T U 
V W X Y Z [ \ 


In [2]:
a=[1,2,3]
b=a
b[0]=10
print(a)
print(b)

[10, 2, 3]
[10, 2, 3]


In [6]:
x="card"
for i in x:
    print(i)
    i.upper()

c
a
r
d


In [8]:
x=[0,1,2,3]
for i in x:
    x.remove(i)
print(x)    

[1, 3]


In [10]:
tuple=(1,2,[3,4])
tuple[2][0]=10
tuple

(1, 2, [10, 4])

In [11]:
for i in range(5):
    if i==4:
        break
else:
    print("completed")    

In [12]:
for i in range(5):
    if i==7:
        break
else:
    print("completed")    

completed


In [19]:
n="Musk"
print(n[20:1:-1])

ks


In [21]:
for i in range(3):
    print(i)
else:
    print(3)    

0
1
2
3


In [10]:
#isspace
a="hello"
print(a.isspace())
d=" "
print(d.isspace())

False
True


In [16]:
def fun(x):
    x.append(4)

l=[1,2,3]
y=fun(l)
print(l)
print(y)

[1, 2, 3, 4]
None


In [23]:
def fun(x):
    x.append(4)
    return x
l=[1,2,3]
y=fun(l)
print(l)
print(y)

[1, 2, 3, 4]
[1, 2, 3, 4]


In [2]:
#splitting list into 2 equal
l=[1,2,3,4,5,6,7,8,9,10]
mid=len(l)//2
print(len(l))
l1=l[:mid]
l2=l[mid:]
print(l1)
print(l2)

10
[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]


In [1]:
a="hello world"
words=a.split()
print(len(words))

2


In [6]:
i="".join(["1","2"])
io="+".join(["1","2"])
print(i)
print(io)

12
1+2


In [4]:
#global
global_var=20
def myfun():
    # global global_var
    # global_var=30
    print(global_var)

myfun()    
print(myfun())

20
20
None


In [5]:
i=3
j=3
while i:
    while j:
        print(i,j)
        j-=1
    i-=1
print(i,j)        

3 3
3 2
3 1
0 0


In [ ]:
# infinite loop
# i=4
# j=2
# while i:
#     while j:
#         print(i,j)
#         j-=1
#         i-=1
#     print(i,j)        

In [3]:
d={"a":1,"b":2,"c":3}
for i in list(d):
    if i=="a":
        d.pop(i)
    else:
        print(d[i])    

2
3


In [13]:
d={"a":1,"b":2,"c":3}
x=d.keys()
d["d"]=3
print(list(x))

['a', 'b', 'c', 'd']


In [14]:
name="python"
num=0
print(name[1]+str(bool(num)))

yFalse


In [1]:
def fun(x,y):
    return x if y>0 else y

result=fun(5,0)+fun(0,-5)
result

-5

In [12]:
def f(x=[]):
    x.append(1)
    return x

print(f())
print(f())
print(f())

[1]
[1, 1]
[1, 1, 1]


In [14]:
def f(x=None):
    if x==None:
     x=[]
     x.append(1)
    return x

print(f())
print(f())
print(f())

[1]
[1]
[1]


In [57]:
#string methods
text="hello"
print(len(text))

print(text.lower())

print(text.upper())

t=" hello  "
print(t.strip())

a="hello world"
print(a.replace("world","hi"))

text="hello world"
print(text.split())
print(text.split("o"))
print(text.split("o",1))
print(text.split("o",2))

text="hello world"
print(text.find("o",3))

text=["hello","world"]
print(" ".join(text))
print("+".join(text))

text="hello"
print(text.startswith("hello"))
print(text.startswith("h"))

print(text.endswith("o"))

t="hello"
print(t.capitalize())

t="hello"
print(t.title())

text="Hello world"
print(text.swapcase())

5
hello
HELLO
hello
hello hi
['hello', 'world']
['hell', ' w', 'rld']
['hell', ' world']
['hell', ' w', 'rld']
4
hello world
hello+world
True
True
True
Hello
Hello
hELLO WORLD


In [60]:
a="hello world world"
print(a.replace("world","hi",1))

hello hi world


In [50]:
#sets
set={1,2,3,3,2}
set

{1, 2, 3}

In [51]:
set.add(4)
print(set)
set.remove(3)# error if 3 is not found
print(set)
set.discard(5)# shows no error if not found
print(set)

{1, 2, 3, 4}
{1, 2, 4}
{1, 2, 4}


In [53]:
set.pop()# removes first element
print(set)

{2, 4}


In [54]:
set.clear()

In [61]:
set1={1,2,3,5,6,8,3,9}
set2={6,8,4,3,1,2,9,7}
print("union:",set1.union(set2)) 
print("intersection:", set1&set2 ) 
print("differences:", set1-set2 ) 


union: {1, 2, 3, 4, 5, 6, 7, 8, 9}
intersection: {1, 2, 3, 6, 8, 9}
differences: {5}


In [66]:
i=len(set("banana"))
i

3

In [68]:
import random
print(random.randint(1,100))

77


In [69]:
print(random.randrange(1,50,4))

21


In [ ]:
print(random.uniform(1,100))

82.35228382316089


85

In [83]:
fruits=["cherry","apple","orange"]
print(random.choice(fruits))

cherry


In [92]:
asci=65
for i in range(8):
    for j in range(i):
        if chr(asci) == "Z":
            break
        else:
          print(chr(asci),end=" ")
          asci+=1
    print()    


A 
B C 
D E F 
G H I J 
K L M N O 
P Q R S T U 
V W X Y 


### Numpy

In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3])
print(a)
a[2]

[1 2 3]


np.int64(3)

In [8]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [13]:
print(a)

[1 2 3 4]


In [18]:
a=np.array([[1,2,3],
           [4,5,6]])
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
#basic array operations
import numpy as np
a1=np.array([1,2,3,4])
print(a1.ndim)
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2.ndim)
print(a2.size)
print(a2.shape)

1
2
9
(3, 3)


In [6]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.arange(1,5)

array([1, 2, 3, 4])

In [9]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [17]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
a.reshape(3,2)

(2, 3)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [21]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [25]:
print(a.min())
print(a.max())
print(a.sum())

1
6
21


In [12]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.sum(axis=0))
print(a.sum(axis=1))
print(np.sqrt(a))
print(np.std(a))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
2.581988897471611


In [20]:
#indexing and slicing

import numpy as np
n=[6,7,8]
print(n[0:2])
print(n[-1])

[6, 7]
8


In [27]:
a=np.array([[6,7,8],[1,2,3],[4,5,6]])
print(a)
print(a[1,2])
print(a[:,1:])

[[6 7 8]
 [1 2 3]
 [4 5 6]]
3
[[7 8]
 [2 3]
 [5 6]]


In [39]:
#iterating through arrays
a=np.array([[6,7,8],[1,2,3],[4,5,6]])
print(a)
for row in a:
    print(row+1)

for cell in a.flat:
    print(cell)




[[6 7 8]
 [1 2 3]
 [4 5 6]]
[7 8 9]
[2 3 4]
[5 6 7]
6
7
8
1
2
3
4
5
6


In [ ]:
#stacking together two arrays

a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
print(a)
print()
print(b)

[[0 1]
 [2 3]
 [4 5]]

[[ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [52]:
print(a.reshape(2,3))
a

[[0 1 2]
 [3 4 5]]


array([[0, 1],
       [2, 3],
       [4, 5]])

In [47]:
print(np.vstack((a,b)))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [48]:
print(np.hstack((a,b)))

[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [54]:
a1=np.arange(10).reshape(2,5)
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
w=np.vsplit(a1,2)
w[0]

array([[0, 1, 2, 3, 4]])

In [68]:
a1=np.arange(1,31).reshape(2,15)
a1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [69]:
w=np.hsplit(a1,3)
w[0]

array([[ 1,  2,  3,  4,  5],
       [16, 17, 18, 19, 20]])

In [13]:
#indexing with boolean arrays

a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
b=a>4
b

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [15]:
a[b] #printing only the true values

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
a[b]=-1
a

array([[ 1,  2,  3,  4],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [ ]:
#regular expression